version: 0.2

env:
  variables:
    REGION: "us-west-2"
    CAPABILITIES: "CAPABILITY_NAMED_IAM"
    NETWORK_STACK_NAME: "NetworkStack"

phases:
  install:
    runtime-versions:
      python: 3.8
      ruby: 2.6.0
    commands:
      - echo Installing AWS CLI and jq
      - pip install awscli --upgrade --quiet
      - pip install cfn-lint --quiet
      - yum install -y jq

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws --version
      - jq --version

  build:
    commands:
      - cd ./templates
      - cfn-lint *.yaml
      - echo Deploying Network Stack
      - aws cloudformation create-stack --stack-name MyStack --template-body file://s3.yaml --capabilities CAPABILITY_NAMED_IAM
      
  post_build:
    commands:
      - echo All stacks deployed successfully.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
